// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // datasource.url is defined in schema.prisma via env("DATABASE_URL")
  // Defining it here AND in schema.prisma causes a Vercel build conflict
});
